name: chess_pgn_converter
description: Convert chess books to PGN files

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # JSON serialization
  json_annotation: ^4.11.0

  # File & Storage
  file_picker: ^11.0.2
  path_provider: ^2.1.5

  # Sharing
  share_plus: ^12.0.2

  # UI Enhancements
  google_fonts: ^8.1.0

  # Chess rules validation
  chess: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # JSON generation
  build_runner: ^2.15.0
  json_serializable: ^6.13.2

flutter:
  uses-material-design: true
